name: Test
on:
  push:

jobs:
  pitest:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Gradle Test
        run: ./gradlew test --no-daemon
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
         name: Rankup3
         path: build/
